[2024-07-28T23:32:37.502+0000] {processor.py:161} INFO - Started process (PID=537) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:32:37.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:32:37.517+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:32:37.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:32:37.618+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:32:37.598+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:32:37.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:32:37.769+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.290 seconds
[2024-07-28T23:33:09.177+0000] {processor.py:161} INFO - Started process (PID=539) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:33:09.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:33:09.190+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:33:09.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:33:09.329+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:33:09.314+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:33:09.341+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:33:09.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.355 seconds
[2024-07-28T23:33:40.497+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:33:40.499+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:33:40.502+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:33:40.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:33:40.560+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:33:40.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:33:40.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:33:40.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.146 seconds
[2024-07-28T23:34:10.983+0000] {processor.py:161} INFO - Started process (PID=543) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:34:10.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:34:10.988+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:34:10.988+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:34:11.040+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:34:11.026+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:34:11.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:34:11.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.150 seconds
[2024-07-28T23:34:41.723+0000] {processor.py:161} INFO - Started process (PID=545) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:34:41.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:34:41.728+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:34:41.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:34:41.784+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:34:41.772+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:34:41.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:34:41.866+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.152 seconds
[2024-07-28T23:35:12.106+0000] {processor.py:161} INFO - Started process (PID=547) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:35:12.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:35:12.111+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:35:12.111+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:35:12.156+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:35:12.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:35:12.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:35:12.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.150 seconds
[2024-07-28T23:35:42.890+0000] {processor.py:161} INFO - Started process (PID=549) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:35:42.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:35:42.897+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:35:42.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:35:42.956+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:35:42.947+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:35:42.961+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:35:43.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.173 seconds
[2024-07-28T23:36:13.372+0000] {processor.py:161} INFO - Started process (PID=550) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:36:13.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:36:13.379+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:36:13.378+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:36:13.434+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:36:13.423+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:36:13.439+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:36:13.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.181 seconds
[2024-07-28T23:36:43.981+0000] {processor.py:161} INFO - Started process (PID=552) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:36:43.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:36:43.998+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:36:43.997+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:36:44.106+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:36:44.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:36:44.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:36:44.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.285 seconds
[2024-07-28T23:37:15.238+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:37:15.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:37:15.246+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:37:15.245+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:37:15.415+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:37:15.385+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:37:15.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:37:15.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.427 seconds
[2024-07-28T23:37:46.120+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:37:46.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:37:46.128+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:37:46.127+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:37:46.200+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:37:46.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:37:46.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:37:46.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.225 seconds
[2024-07-28T23:38:18.051+0000] {processor.py:161} INFO - Started process (PID=558) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:38:18.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:38:18.071+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:38:18.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:38:18.219+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:38:18.193+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:38:18.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:38:18.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.405 seconds
[2024-07-28T23:38:49.414+0000] {processor.py:161} INFO - Started process (PID=560) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:38:49.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:38:49.428+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:38:49.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:38:49.518+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:38:49.504+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:38:49.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:38:49.630+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.237 seconds
[2024-07-28T23:39:20.697+0000] {processor.py:161} INFO - Started process (PID=562) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:39:20.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:39:20.703+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:39:20.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:39:20.766+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:39:20.755+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:39:20.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:39:20.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.190 seconds
[2024-07-28T23:39:51.078+0000] {processor.py:161} INFO - Started process (PID=564) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:39:51.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:39:51.095+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:39:51.094+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:39:51.164+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:39:51.153+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:39:51.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:39:51.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.178 seconds
[2024-07-28T23:40:22.237+0000] {processor.py:161} INFO - Started process (PID=566) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:40:22.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:40:22.265+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:40:22.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:40:22.371+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:40:22.354+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:40:22.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:40:22.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.314 seconds
[2024-07-28T23:40:52.676+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:40:52.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:40:52.693+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:40:52.692+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:40:52.793+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:40:52.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:40:52.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:40:52.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.291 seconds
[2024-07-28T23:41:24.007+0000] {processor.py:161} INFO - Started process (PID=570) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:41:24.012+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:41:24.016+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:41:24.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:41:24.145+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:41:24.124+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:41:24.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:41:24.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.318 seconds
[2024-07-28T23:41:54.930+0000] {processor.py:161} INFO - Started process (PID=572) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:41:54.932+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:41:54.935+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:41:54.935+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:41:55.003+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:41:54.989+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:41:55.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:41:55.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.185 seconds
[2024-07-28T23:42:27.648+0000] {processor.py:161} INFO - Started process (PID=574) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:42:27.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:42:27.673+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:42:27.671+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:42:28.115+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:42:28.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:42:28.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:42:28.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.917 seconds
[2024-07-28T23:42:59.262+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:42:59.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:42:59.268+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:42:59.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:42:59.336+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:42:59.322+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:42:59.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:42:59.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.162 seconds
[2024-07-28T23:43:29.624+0000] {processor.py:161} INFO - Started process (PID=578) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:43:29.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:43:29.630+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:43:29.629+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:43:29.681+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:43:29.670+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:43:29.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:43:29.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.164 seconds
[2024-07-28T23:44:00.707+0000] {processor.py:161} INFO - Started process (PID=580) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:44:00.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:44:00.716+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:44:00.715+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:44:00.770+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:44:00.758+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:44:00.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:44:00.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.148 seconds
[2024-07-28T23:44:31.192+0000] {processor.py:161} INFO - Started process (PID=582) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:44:31.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:44:31.206+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:44:31.204+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:44:31.271+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:44:31.261+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:44:31.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:44:31.353+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.184 seconds
[2024-07-28T23:45:01.556+0000] {processor.py:161} INFO - Started process (PID=584) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:45:01.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:45:01.562+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:45:01.562+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:45:01.635+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:45:01.622+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:45:01.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:45:01.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.187 seconds
[2024-07-28T23:45:33.285+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:45:33.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:45:33.291+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:45:33.290+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:45:33.339+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:45:33.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:45:33.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:45:33.413+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.137 seconds
[2024-07-28T23:46:03.857+0000] {processor.py:161} INFO - Started process (PID=588) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:46:03.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:46:03.864+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:46:03.864+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:46:03.951+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:46:03.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:46:03.960+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:46:04.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.215 seconds
[2024-07-28T23:46:35.251+0000] {processor.py:161} INFO - Started process (PID=590) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:46:35.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:46:35.256+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:46:35.256+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:46:35.305+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:46:35.294+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:46:35.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:46:35.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.159 seconds
[2024-07-28T23:47:06.648+0000] {processor.py:161} INFO - Started process (PID=592) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:47:06.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:47:06.654+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:47:06.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:47:06.720+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:47:06.706+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:47:06.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:47:06.807+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.169 seconds
[2024-07-28T23:47:37.974+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:47:37.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:47:37.996+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:47:37.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:47:38.249+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:47:38.214+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:47:38.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:47:38.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.522 seconds
[2024-07-28T23:48:09.434+0000] {processor.py:161} INFO - Started process (PID=596) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:48:09.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:48:09.439+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:48:09.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:48:09.501+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:48:09.488+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:48:09.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:48:09.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.179 seconds
[2024-07-28T23:48:40.304+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:48:40.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:48:40.309+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:48:40.308+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:48:40.380+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:48:40.366+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:48:40.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:48:40.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.170 seconds
[2024-07-28T23:49:11.281+0000] {processor.py:161} INFO - Started process (PID=600) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:49:11.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:49:11.286+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:49:11.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:49:11.352+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:49:11.338+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:49:11.358+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:49:11.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.172 seconds
[2024-07-28T23:49:42.075+0000] {processor.py:161} INFO - Started process (PID=602) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:49:42.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:49:42.081+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:49:42.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:49:42.136+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:49:42.125+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:49:42.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:49:42.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.162 seconds
[2024-07-28T23:50:12.828+0000] {processor.py:161} INFO - Started process (PID=604) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:50:12.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:50:12.837+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:50:12.836+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:50:12.916+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:50:12.899+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:50:12.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:50:12.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.183 seconds
[2024-07-28T23:50:43.835+0000] {processor.py:161} INFO - Started process (PID=606) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:50:43.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:50:43.841+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:50:43.840+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:50:43.902+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:50:43.893+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:50:43.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:50:43.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.152 seconds
[2024-07-28T23:51:14.481+0000] {processor.py:161} INFO - Started process (PID=608) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:51:14.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:51:14.486+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:51:14.486+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:51:14.562+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:51:14.550+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:51:14.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:51:14.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.192 seconds
[2024-07-28T23:51:45.378+0000] {processor.py:161} INFO - Started process (PID=610) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:51:45.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:51:45.384+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:51:45.383+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:51:45.446+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:51:45.434+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:51:45.450+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:51:45.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.188 seconds
[2024-07-28T23:52:16.318+0000] {processor.py:161} INFO - Started process (PID=612) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:52:16.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:52:16.323+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:52:16.323+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:52:16.379+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:52:16.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:52:16.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:52:16.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.149 seconds
[2024-07-28T23:52:47.205+0000] {processor.py:161} INFO - Started process (PID=614) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:52:47.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:52:47.213+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:52:47.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:52:47.262+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:52:47.252+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:52:47.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:52:47.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.141 seconds
[2024-07-28T23:53:18.111+0000] {processor.py:161} INFO - Started process (PID=616) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:53:18.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:53:18.118+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:53:18.117+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:53:18.175+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:53:18.165+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:53:18.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:53:18.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.159 seconds
[2024-07-28T23:53:48.629+0000] {processor.py:161} INFO - Started process (PID=618) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:53:48.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:53:48.634+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:53:48.634+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:53:48.687+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:53:48.678+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:53:48.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:53:48.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.150 seconds
[2024-07-28T23:54:19.613+0000] {processor.py:161} INFO - Started process (PID=620) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:54:19.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:54:19.619+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:54:19.618+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:54:19.685+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:54:19.671+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:54:19.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:54:19.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.202 seconds
[2024-07-28T23:54:50.608+0000] {processor.py:161} INFO - Started process (PID=622) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:54:50.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:54:50.614+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:54:50.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:54:50.684+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:54:50.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:54:50.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:54:50.771+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.173 seconds
[2024-07-28T23:55:21.285+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:55:21.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:55:21.290+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:55:21.289+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:55:21.338+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:55:21.329+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:55:21.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:55:21.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.132 seconds
[2024-07-28T23:55:52.263+0000] {processor.py:161} INFO - Started process (PID=626) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:55:52.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:55:52.268+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:55:52.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:55:52.334+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:55:52.320+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:55:52.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:55:52.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.172 seconds
[2024-07-28T23:56:22.980+0000] {processor.py:161} INFO - Started process (PID=628) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:56:22.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:56:22.985+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:56:22.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:56:23.052+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:56:23.040+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:56:23.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:56:23.145+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.174 seconds
[2024-07-28T23:56:53.902+0000] {processor.py:161} INFO - Started process (PID=630) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:56:53.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:56:53.921+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:56:53.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:56:54.242+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:56:54.199+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:56:54.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:56:54.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.658 seconds
[2024-07-28T23:57:25.522+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:57:25.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:57:25.528+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:57:25.527+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:57:25.610+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:57:25.594+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:57:25.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:57:25.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.212 seconds
[2024-07-28T23:57:56.005+0000] {processor.py:161} INFO - Started process (PID=634) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:57:56.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:57:56.011+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:57:56.010+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:57:56.075+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:57:56.062+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:57:56.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:57:56.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.165 seconds
[2024-07-28T23:58:27.243+0000] {processor.py:161} INFO - Started process (PID=636) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:58:27.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:58:27.249+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:58:27.249+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:58:27.316+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:58:27.302+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:58:27.321+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:58:27.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.171 seconds
[2024-07-28T23:58:58.215+0000] {processor.py:161} INFO - Started process (PID=638) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:58:58.216+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:58:58.219+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:58:58.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:58:58.268+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:58:58.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:58:58.273+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:58:58.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.160 seconds
[2024-07-28T23:59:28.993+0000] {processor.py:161} INFO - Started process (PID=640) to work on /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:59:28.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/exchange_rate_pipeline.py for tasks to queue
[2024-07-28T23:59:28.999+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:59:28.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:59:29.056+0000] {logging_mixin.py:188} INFO - [2024-07-28T23:59:29.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/exchange_rate_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/exchange_rate_pipeline.py", line 7, in <module>
    from clean_data import clean_data
ModuleNotFoundError: No module named 'clean_data'
[2024-07-28T23:59:29.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/exchange_rate_pipeline.py
[2024-07-28T23:59:29.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/exchange_rate_pipeline.py took 0.159 seconds
